CREATE DATABASE ecommerce_sales;

USE ecommerce_sales;


-- =====================================================
-- 1. CREATE TABLES
-- =====================================================

CREATE TABLE customers (
    customer_id INT PRIMARY KEY,
    customer_name VARCHAR(100),
    city VARCHAR(50),
    signup_date DATE
);

CREATE TABLE products (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(100),
    category VARCHAR(50),
    price DECIMAL(10,2)
);

CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    customer_id INT,
    product_id INT,
    order_date DATE,
    quantity INT,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id)
);


-- =====================================================
-- 2. INSERT DATA
-- =====================================================

INSERT INTO customers VALUES
(1, 'Rahul', 'Delhi', '2024-01-15'),
(2, 'Priya', 'Mumbai', '2024-02-10'),
(3, 'Amit', 'Bangalore', '2024-02-20'),
(4, 'Neha', 'Delhi', '2024-03-05'),
(5, 'Rohan', 'Pune', '2024-03-15'),
(6, 'Sneha', 'Mumbai', '2024-04-01'),
(7, 'Vikas', 'Hyderabad', '2024-04-12'),
(8, 'Anjali', 'Bangalore', '2024-05-10');

INSERT INTO products VALUES
(101, 'Laptop', 'Electronics', 55000),
(102, 'Smartphone', 'Electronics', 30000),
(103, 'Headphones', 'Electronics', 3000),
(104, 'Office Chair', 'Furniture', 12000),
(105, 'Desk', 'Furniture', 15000),
(106, 'Keyboard', 'Accessories', 2500),
(107, 'Mouse', 'Accessories', 1500),
(108, 'Monitor', 'Electronics', 18000);

INSERT INTO orders VALUES
(1001, 1, 101, '2024-04-10', 1),
(1002, 2, 102, '2024-04-12', 2),
(1003, 3, 103, '2024-04-15', 3),
(1004, 1, 106, '2024-04-20', 2),
(1005, 4, 104, '2024-05-02', 1),
(1006, 5, 105, '2024-05-05', 1),
(1007, 2, 108, '2024-05-10', 2),
(1008, 6, 102, '2024-05-15', 1),
(1009, 7, 107, '2024-05-20', 4),
(1010, 8, 101, '2024-06-01', 1),
(1011, 3, 108, '2024-06-05', 1),
(1012, 1, 103, '2024-06-10', 2),
(1013, 4, 106, '2024-06-15', 3),
(1014, 5, 102, '2024-06-20', 1),
(1015, 6, 104, '2024-06-25', 2);


-- =====================================================
-- 3. TOTAL REVENUE GENERATED BY EACH CUSTOMER
-- =====================================================

WITH customer_rev AS (
    SELECT
        customers.customer_id,
        customers.customer_name,
        customers.city,
        SUM(orders.quantity * products.price) AS total_revenue
    FROM customers
    INNER JOIN orders
        ON customers.customer_id = orders.customer_id
    INNER JOIN products
        ON orders.product_id = products.product_id
    GROUP BY customers.customer_id
)
SELECT
    customer_id,
    UPPER(customer_name) AS customer_name,
    city,
    total_revenue
FROM customer_rev
ORDER BY total_revenue DESC;


-- =====================================================
-- 4. CUSTOMERS WITH MORE THAN 50,000 REVENUE
-- =====================================================

SELECT
    customers.customer_id,
    customers.customer_name,
    customers.city,
    SUM(orders.quantity * products.price) AS total_revenue
FROM customers
INNER JOIN orders
    ON customers.customer_id = orders.customer_id
INNER JOIN products
    ON orders.product_id = products.product_id
GROUP BY customers.customer_id
HAVING total_revenue > 50000
ORDER BY total_revenue DESC;


-- =====================================================
-- 5. TOP-SELLING PRODUCTS (INCLUDING TIES)
-- =====================================================

WITH product_sales AS (
    SELECT
        products.product_id,
        products.product_name,
        products.category,
        SUM(orders.quantity) AS total_unit_sold
    FROM orders
    INNER JOIN products
        ON orders.product_id = products.product_id
    GROUP BY products.product_id
),
sales_rank AS (
    SELECT
        product_id,
        product_name,
        category,
        total_unit_sold,
        DENSE_RANK() OVER (
            ORDER BY total_unit_sold DESC
        ) AS ranked_sales
    FROM product_sales
)
SELECT
    product_id,
    product_name,
    category,
    total_unit_sold
FROM sales_rank
WHERE ranked_sales = 1;


-- =====================================================
-- 6. REVENUE BY CITY
-- =====================================================

SELECT
    customers.city,
    SUM(products.price * orders.quantity) AS total_revenue
FROM customers
INNER JOIN orders
    ON customers.customer_id = orders.customer_id
INNER JOIN products
    ON orders.product_id = products.product_id
GROUP BY customers.city
ORDER BY total_revenue DESC;


-- =====================================================
-- 7. MONTHLY REVENUE
-- =====================================================

SELECT
    DATE_FORMAT(orders.order_date, '%Y-%m') AS month,
    SUM(orders.quantity * products.price) AS total_revenue
FROM orders
INNER JOIN products
    ON orders.product_id = products.product_id
GROUP BY DATE_FORMAT(orders.order_date, '%Y-%m')
ORDER BY DATE_FORMAT(orders.order_date, '%Y-%m');


-- =====================================================
-- 8. CUSTOMERS WITH MORE THAN ONE ORDER
-- =====================================================

WITH customer_orders AS (
    SELECT
        customers.customer_id,
        customers.customer_name,
        COUNT(orders.order_id) AS total_orders
    FROM customers
    LEFT JOIN orders
        ON customers.customer_id = orders.customer_id
    GROUP BY customers.customer_id
)
SELECT
    customer_id,
    customer_name,
    total_orders
FROM customer_orders
WHERE total_orders > 1
ORDER BY total_orders DESC;


-- =====================================================
-- 9. CUSTOMERS WHO NEVER ORDERED
-- =====================================================

SELECT
    customers.customer_id,
    customers.customer_name,
    customers.city
FROM customers
LEFT JOIN orders
    ON customers.customer_id = orders.customer_id
WHERE orders.order_id IS NULL
ORDER BY customers.customer_id;


-- =====================================================
-- 10. AVERAGE ORDER VALUE
-- =====================================================

SELECT
    ROUND(
        AVG(orders.quantity * products.price),
        2
    ) AS average_order_value
FROM orders
INNER JOIN products
    ON orders.product_id = products.product_id;


-- =====================================================
-- 11. REVENUE BY PRODUCT CATEGORY + CONTRIBUTION %
-- =====================================================

WITH product_rev AS (
    SELECT
        products.category,
        SUM(products.price * orders.quantity) AS category_revenue
    FROM products
    INNER JOIN orders
        ON products.product_id = orders.product_id
    GROUP BY products.category
),
rev_percent AS (
    SELECT
        category,
        category_revenue,
        SUM(category_revenue) OVER() AS total_revenue
    FROM product_rev
)
SELECT
    category,
    category_revenue,
    ROUND(
        category_revenue / total_revenue * 100,
        2
    ) AS percentage_contribution
FROM rev_percent
ORDER BY category_revenue DESC;


-- =====================================================
-- 12. CUSTOMER REVENUE + ORDER COUNT
-- =====================================================

WITH customer_data AS (
    SELECT
        customers.customer_id,
        customers.customer_name,
        COUNT(orders.order_id) AS total_orders,
        COALESCE(
            SUM(orders.quantity * products.price),
            0
        ) AS total_revenue
    FROM orders
    INNER JOIN customers
        ON orders.customer_id = customers.customer_id
    INNER JOIN products
        ON orders.product_id = products.product_id
    GROUP BY customers.customer_id
)
SELECT
    customer_id,
    customer_name,
    total_orders,
    total_revenue
FROM customer_data
ORDER BY total_revenue DESC;


-- =====================================================
-- 13. PRODUCT PERFORMANCE
-- =====================================================

WITH product_performance AS (
    SELECT
        products.product_id,
        products.product_name,
        COALESCE(SUM(orders.quantity), 0) AS total_unit_sold,
        COALESCE(
            SUM(orders.quantity * products.price),
            0
        ) AS total_revenue
    FROM products
    LEFT JOIN orders
        ON products.product_id = orders.product_id
    GROUP BY products.product_id, products.product_name
)
SELECT
    product_id,
    product_name,
    total_unit_sold,
    total_revenue
FROM product_performance
ORDER BY total_revenue DESC;